SELECT * FROM funcionarios;
SELECT * FROM veiculos;
SELECT * FROM salarios;

SELECT * FROM FUNCIONARIOS
SELECT * FROM FUNCIONARIOS WHERE SALARIO > 2000;
SELECT * FROM FUNCIONARIOS WHERE NOME = 'José';
SELECT * FROM FUNCIONARIOS WHERE funcionario_id = 9;

SELECT NOME AS 'Funcionário', SALARIO FROM FUNCIONARIOS F WHERE F.SALARIO > 2000; 
