ALTER TABLE ALUNOS ADD DATA_NASCIMENTO VARCHAR2(10);

ALTER TABLE ALUNOS MODIFY (DATA_NASCIMENTO date);
ALTER TABLE ALUNOS RENAME COLUMN DATA_NASCIMENTO TO NASCIMENTO;

ALTER TABLE INSTRUTOR ADD EMAIL VARCHAR2(100);

ALTER TABLE INSTRUTOR drop column EMAIL;

--

ALTER TABLE CURSOS ADD INSTRUTOR VARCHAR2(45);

ALTER TABLE CURSOS ADD CONSTRAINT FK_INSTRUTOR foreign key (INSTRUTOR) references INSTRUTOR (CODIGO);

--/////////////////////--

ALTER TABLE DADOS_COMPRA ADD CONSTRAINT FK_ALUNOS FOREIGN KEY (ALUNOS) REFERENCES ALUNOS (CODIGO);


ALTER TABLE DETALHES_COMPRA ADD CONSTRAINT FK_CURSO FOREIGN KEY (CURSO) REFERENCES CURSOS (CODIGO);

ALTER TABLE DETALHES_COMPRA ADD CONSTRAINT FK_PEDIDO FOREIGN KEY (PEDIDO) REFERENCES DADOS_COMPRA (CODIGO);
