--EXERCÍCIO 2

SELECT * FROM ALUNOS;

SELECT NOME FROM CURSOS;

SELECT NOME, PRECO FROM CURSOS C WHERE C.PRECO > 200;

SELECT NOME, PRECO FROM CURSOS C WHERE C.PRECO > 200 AND C.PRECO < 300;

SELECT * FROM DADOS_COMPRA WHERE TO_DATE(DIA, 'DD/MM/RRRR') BETWEEN TO_DATE('15/04/2010', 'DD/MM/RRRR') AND TO_DATE('18/04/2010', 'DD/MM/RRRR'); 

SELECT * FROM DADOS_COMPRA WHERE DIA = ('15/04/2010');
