--EXERCÍCIO 3

SELECT * FROM ALUNOS;

SELECT * FROM CURSOS;

UPDATE ALUNOS SET ENDERECO = 'Av. Brasil 778' WHERE CODIGO = 'A1'; --ALUNO = 'José';

UPDATE ALUNOS SET EMAILS = 'cristiano@softblue.com.br' WHERE CODIGO = 'A4';

UPDATE CURSOS SET PRECO = PRECO * 1.1 WHERE PRECO < 300;

UPDATE CURSOS SET NOME = 'PHP Fundamentos' WHERE CODIGO = 'C4';
