--SELECT * FROM CURSOS_SOFTBLUE;
--SELECT * FROM INFORMACOES_ALUNOS;

SELECT * FROM CURSOS;
SELECT * FROM TIPO;
SELECT * FROM INSTRUTOR;

SELECT * FROM ALUNOS;

--SELECT * FROM COMPRAS;

SELECT * FROM DADOS_COMPRA;
SELECT * FROM DETALHES_COMPRA;
