INSERT INTO VEICULOS (FUNCIONARIO_ID, VEICULO, PLACA) VALUES (NULL, 'Moto','SB-0003');

--INSERT CPF

INSERT INTO CPF (ID_, CPF) VALUES (7, '111.111.111-11');
INSERT INTO CPF (ID_, CPF) VALUES (8, '222.222.222-22');
INSERT INTO CPF (ID_, CPF) VALUES (9, '333.333.333-33');
INSERT INTO CPF (ID_, CPF) VALUES (11, '555.555.555-55');

INSERT INTO CLIENTES (NOME, QUEM_INDICOU) VALUES ('André', NULL);
INSERT INTO CLIENTES (NOME, QUEM_INDICOU) VALUES ('Samuel', 1);
INSERT INTO CLIENTES (NOME, QUEM_INDICOU) VALUES ('Carlos', 2);
INSERT INTO CLIENTES (NOME, QUEM_INDICOU) VALUES ('Rafael', 1); 

