CREATE TABLE CPF
(
  ID_ NUMBER NOT NULL,
  CPF VARCHAR2(14),
  PRIMARY KEY(ID_),
  CONSTRAINT FK_CPF FOREIGN KEY (ID_) REFERENCES FUNCIONARIOS (ID_)
);

CREATE TABLE CLIENTES
(
  ID_ NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
  NOME VARCHAR2(45) NOT NULL,
  QUEM_INDICOU NUMBER,
  PRIMARY KEY(ID_),
  CONSTRAINT FK_QUEM_INDICOU FOREIGN KEY (QUEM_INDICOU) REFERENCES CLIENTES (ID_)
);
