--EXERCÍCIO 1
SELECT * FROM CURSOS;
SELECT * FROM TIPO;
SELECT * FROM INSTRUTOR;
SELECT * FROM ALUNOS;
SELECT * FROM DADOS_COMPRA;
SELECT * FROM DETALHES_COMPRA;

SELECT ALUNO FROM ALUNOS WHERE CODIGO = 'A2';

SELECT ALUNO FROM ALUNOS WHERE CODIGO = 'A6';

SELECT ALUNO FROM ALUNOS WHERE CODIGO = 'A4';

SELECT COUNT(NOME) FROM CURSOS;

SELECT SUM(PRECO) FROM CURSOS;

SELECT AVG(PRECO) FROM DETALHES_COMPRA;

SELECT MAX(PRECO) FROM CURSOS;

SELECT MIN(PRECO) FROM CURSOS;

SELECT SUM(PRECO) FROM DETALHES_COMPRA;

SELECT PEDIDO, SUM(PRECO)
  FROM DETALHES_COMPRA
 GROUP BY PEDIDO
 ORDER BY SUM(PRECO) DESC;

SELECT I.NOME, COUNT(C.CODIGO) AS QUANT_CODIGO
  FROM INSTRUTOR I
 INNER JOIN CURSOS C
    ON I.CODIGO = C.INSTRUTOR
 GROUP BY I.NOME;

SELECT DC.PEDIDO, A.ALUNO, SUM(DC.PRECO)
  FROM DADOS_COMPRA D
 INNER JOIN ALUNOS A
    ON D.ALUNO = A.CODIGO
 INNER JOIN DETALHES_COMPRA DC
    ON D.CODIGO = DC.PEDIDO HAVING SUM(DC.PRECO) > 500
 GROUP BY DC.PEDIDO, A.ALUNO;

 SELECT DC.PEDIDO, A.ALUNO, COUNT (DC.CURSO)
  FROM DADOS_COMPRA D
 INNER JOIN ALUNOS A
    ON D.ALUNO = A.CODIGO
 INNER JOIN DETALHES_COMPRA DC
    ON D.CODIGO = DC.PEDIDO HAVING COUNT (DC.CURSO) >= 2
 GROUP BY DC.PEDIDO, A.ALUNO;

SELECT ALUNO, ENDERECO FROM ALUNOS WHERE ENDERECO LIKE 'Av.%';

SELECT NOME FROM CURSOS WHERE NOME LIKE 'Java%';
