SELECT * FROM FUNCIONARIOS;

SELECT COUNT(*) FROM FUNCIONARIOS;
SELECT COUNT(*) FROM FUNCIONARIOS WHERE SALARIO > 1600;
SELECT COUNT(*) FROM FUNCIONARIOS WHERE SALARIO > 1600 AND DEPARTAMENTO = 'JURÍDICO';

SELECT * FROM FUNCIONARIOS WHERE SALARIO > 1600 AND DEPARTAMENTO = 'JURÍDICO';
