SELECT * FROM FUNCIONARIOS WHERE ROWNUM < 3;
SELECT * FROM (SELECT * FROM FUNCIONARIOS OFFSET 1 ROWS) WHERE ROWNUM < 3;

SELECT AVG(SALARIO) FROM FUNCIONARIOS WHERE DEPARTAMENTO = 'TI';
SELECT AVG(SALARIO) FROM FUNCIONARIOS WHERE DEPARTAMENTO = 'Jurídico';

SELECT DEPARTAMENTO, AVG(SALARIO) FROM FUNCIONARIOS GROUP BY DEPARTAMENTO;
SELECT DEPARTAMENTO, AVG(SALARIO) FROM FUNCIONARIOS GROUP BY DEPARTAMENTO HAVING AVG(SALARIO) > 2000;

SELECT DEPARTAMENTO, COUNT(*) FROM FUNCIONARIOS GROUP BY DEPARTAMENTO;

SELECT NOME FROM FUNCIONARIOS 
WHERE DEPARTAMENTO IN 
    (
      SELECT DEPARTAMENTO FROM FUNCIONARIOS GROUP BY DEPARTAMENTO HAVING AVG(SALARIO) > 2000
    );
