SELECT SUM(SALARIO) FROM FUNCIONARIOS;
SELECT SUM(SALARIO) FROM FUNCIONARIOS WHERE DEPARTAMENTO = 'TI';

SELECT AVG(SALARIO) FROM FUNCIONARIOS;
SELECT AVG(SALARIO) FROM FUNCIONARIOS WHERE DEPARTAMENTO = 'TI';

SELECT MAX(SALARIO) FROM FUNCIONARIOS;
SELECT MAX(SALARIO) FROM FUNCIONARIOS WHERE DEPARTAMENTO = 'TI';

SELECT MIN(SALARIO) FROM FUNCIONARIOS;
SELECT MIN(SALARIO) FROM FUNCIONARIOS WHERE DEPARTAMENTO = 'TI';

SELECT DEPARTAMENTO FROM FUNCIONARIOS;
SELECT DISTINCT(DEPARTAMENTO) FROM FUNCIONARIOS;
