SELECT * FROM FUNCIONARIOS;
SELECT * FROM FUNCIONARIOS ORDER BY NOME;
SELECT * FROM FUNCIONARIOS ORDER BY NOME DESC;

SELECT * FROM FUNCIONARIOS ORDER BY SALARIO;
SELECT * FROM FUNCIONARIOS ORDER BY SALARIO DESC;

SELECT * FROM FUNCIONARIOS ORDER BY DEPARTAMENTO;
SELECT * FROM FUNCIONARIOS ORDER BY DEPARTAMENTO, SALARIO;
SELECT * FROM FUNCIONARIOS ORDER BY DEPARTAMENTO DESC, SALARIO DESC;
