--EXERCÍCIO 1
SELECT * FROM CURSOS;
SELECT * FROM TIPO;
SELECT * FROM INSTRUTOR;

SELECT * FROM DADOS_COMPRA;
SELECT * FROM DETALHES_COMPRA;

SELECT C.NOME AS NOME_CURSO, T.NOME AS TIPO_CURSO FROM CURSOS C INNER JOIN TIPO T ON C.TIPO = T.CODIGO; 

SELECT C.NOME AS NOME_CURSO, T.NOME AS TIPO_CURSO, I.NOME AS INSTRUTOR, I.TELEFONE FROM CURSOS C 
INNER JOIN TIPO T ON C.TIPO = T.CODIGO
INNER JOIN INSTRUTOR I ON C.INSTRUTOR = I.CODIGO;

SELECT D.CODIGO AS CODIGO_PEDIDO, D.DIA, D.HORA, DC.CURSO FROM DADOS_COMPRA D 
INNER JOIN DETALHES_COMPRA DC ON D.CODIGO = DC.PEDIDO;

SELECT D.CODIGO AS CODIGO_PEDIDO, D.DIA, D.HORA, C.NOME FROM DADOS_COMPRA D 
INNER JOIN DETALHES_COMPRA DC ON D.CODIGO = DC.PEDIDO
INNER JOIN CURSOS C ON C.CODIGO = DC.CURSO;

SELECT D.CODIGO AS CODIGO_PEDIDO, D.DIA, D.HORA, A.ALUNO, C.NOME FROM DADOS_COMPRA D 
INNER JOIN DETALHES_COMPRA DC ON D.CODIGO = DC.PEDIDO
INNER JOIN CURSOS C ON C.CODIGO = DC.CURSO
INNER JOIN ALUNOS A ON A.CODIGO = D.ALUNO;
